-- Active: 1716401783592@@127.0.0.1@3306@persona
CREATE TABLE PERSONAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE varchar(50),
    APELLIDO varchar(50),
    SEXO varchar(1),
    PESO varchar(10),
    ALTA varchar(1),
    TRABAJA varchar(1)
);
INSERT INTO PERSONAS (NOMBRE, APELLIDO, SEXO, PESO, ALTA, TRABAJA) VALUES
('Sara', 'Presa Garcia', 'F', 54, 'N', 'N'),
('Andrés', 'Soria Prieto', 'M', 88, 'S', 'S'),
('Luisa', 'Tuno Flores', 'F', 62, 'S', 'S'),
('Pedro Luis', 'Rubio Moreno', 'M', 112, 'N', 'N'),
('Ana', 'Sur Requejo', 'F', 92, 'N', 'S');

SELECT NOMBRE, APELLIDO FROM PERSONAS WHERE PESO > 80

SELECT NOMBRE, APELLIDO, SEXO FROM PERSONAS WHERE PESO < 80

SELECT NOMBRE, APELLIDO FROM PERSONAS WHERE PESO < 70 AND PESO > 50

SELECT NOMBRE, APELLIDO FROM PERSONAS WHERE ALTA = 'S' AND TRABAJA = 'S'

SELECT NOMBRE, APELLIDO FROM PERSONAS WHERE ALTA = 'S' or TRABAJA = 'N'

SELECT * FROM PERSONAS WHERE SEXO = 'F'

SELECT * FROM PERSONAS WHERE SEXO = 'F' ORDER BY PESO ASC

SELECT * FROM PERSONAS WHERE SEXO = 'F' ORDER BY PESO DESC

SELECT SUM(PESO) FROM PERSONAS

SELECT SUM(PESO) AS SUMA_PESOS FROM PERSONAS

SELECT COUNT(ID) FROM PERSONAS

SELECT SUM(PESO) AS PESO_BAJOS FROM PERSONAS WHERE ALTA = 'N'

SELECT AVG(PESO) AS PESO_MEDIO_HOMBRES FROM PERSONAS WHERE SEXO = 'M'

SELECT SEXO, COUNT(SEXO) AS NUM_TRABAJADORES FROM PERSONAS WHERE TRABAJA = 'S' GROUP BY SEXO

SELECT SEXO, ALTA, COUNT(*) AS TRABAJADORES FROM PERSONAS WHERE TRABAJA = 'S' GROUP BY SEXO, ALTA

SELECT * FROM PERSONAS WHERE NOMBRE LIKE '%a'

INSERT INTO PERSONAS (NOMBRE, APELLIDO, SEXO, PESO, ALTA, TRABAJA) VALUES
('José', 'Méndez Méndez', 'M', 90, 'S', 'S')

SELECT * FROM PERSONAS

UPDATE PERSONAS SET TRABAJA = 'S' WHERE ID = 1

SELECT * FROM PERSONAS WHERE ID = 1

ALTER TABLE PERSONAS ADD COLUMN EDAD INT;
UPDATE PERSONAS SET EDAD = 21 WHERE ID = 1;
UPDATE PERSONAS SET EDAD = 45 WHERE ID = 2;
UPDATE PERSONAS SET EDAD = 51 WHERE ID = 3;
UPDATE PERSONAS SET EDAD = 68 WHERE ID = 4;
UPDATE PERSONAS SET EDAD = 30 WHERE ID = 5;
UPDATE PERSONAS SET EDAD = 26 WHERE ID = 6;
